c_compiler:              # [win]
  - vs2022               # [win]
cxx_compiler:            # [win]
  - vs2022               # [win]

c_compiler_version:         # [osx]
  - 20                      # [osx]

cxx_compiler_version:       # [osx]
  - 20                      # [osx]
