c_compiler:              # [win]
  - vs2022               # [win]
cxx_compiler:            # [win]
  - vs2022               # [win]
c_stdlib_version:
  - 2022.14

c_compiler_version:         # [osx]
  - 19                      # [osx]
cxx_compiler_version:       # [osx]
  - 19                      # [osx]
